openapi: 3.0.0
info:
  title: League Leaderboard API
  version: 1.0.0
paths:
  /api/leagues/{id}/leaderboard:
    get:
      summary: Get the leaderboard for a specific league
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: The ID of the league
      responses:
        '200':
          description: A list of players ranked for the league
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    rank:
                      type: integer
                    player:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                    totalEventPoints:
                      type: integer
