openapi: 3.0.0
info:
  title: Admin API
  version: 1.0.0
paths:
  /admin/login:
    post:
      summary: Admin login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
  /admin/logout:
    post:
      summary: Admin logout
      responses:
        '200':
          description: Logout successful
components:
  schemas:
    Admin:
      type: object
      properties:
        id:
          type: integer
        email:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
